### ISSUE TITLE
Sync seed.

### ISSUE THREAD

**Issue by Spoiledpay** [alexanderdna/AmeowCoin#2]
Hello,
I put the package in two separate folders and two wallets were created. I noticed that even created and listening on port 6789. They do not sync data. Mine, send but it doesn't reach another wallet. Does it need to be two computers separated by different ip?

thanks

**Comment by alexanderdna** [comment]
Hi! Maybe you can try setting a different port for the second instance. Remember to match your port settings with the peers.txt file for each of the instance so that they can find each other.
