### ISSUE TITLE
Form Appearance Problem

### ISSUE THREAD

**Issue by rschea** [alexanderdna/AmeowCoin#4]
Hi.  I have opened the solution in Visual Studio 2019, but when I run the GUI project, I get the following
![ameowform](https://user-images.githubusercontent.com/106706406/171498004-8080fba1-4386-4e62-8cd7-9bb377dce5ae.PNG)

Can you tell me what is wrong and how I should fix it?

Thank you.

**Comment by alexanderdna** [comment]
Hi! This must be something about scaling on Windows Forms. You can adjust the font size of these form components to smaller values.
